config_version: 1
game_name: battlefield4
global:
  output_dir: G:/Video/Battlefield 4/my_highlights
detection:
  killfeed_roi:
  - 0.42423664122137406
  - 0.6916575890460996
  - 0.17003816793893123
  - 0.19083969465648853
  ocr:
    enabled: true
    keywords:
    - 敵人撃斃
    similarity_threshold: 0.9
    required: false
  templates: {}
  template_dir: models/templates/battlefield_4
  colors:
    white:
      hsv_lower:
      - 81
      - 75
      - 0
      hsv_upper:
      - 121
      - 155
      - 71
      tolerance: 50
  weights:
    ocr: 0.9
    template: 0
    color: 0
    yolo: 0.1
  prefilter:
    enabled: true
    color_threshold: 0.01
  confidence_threshold: 0.5
  rules:
  - name: rule_1
    enabled: true
    require:
    - ocr
    detection_overrides:
      ocr:
        enabled: true
        keywords:
        - 敵人撃斃
        similarity_threshold: 0.9
      killfeed_roi:
      - 0.5540512751145422
      - 0.248
      - 0.20814358713762537
      - 0.10200000000000004
highlights:
  pre_kill_time: 6.0
  post_kill_time: 3.0
  music_path: assets/music/Johan Soderqvist、Patrik Andrén - Battlefield Classic Theme
    - Mayhem View.mp3
video:
  frame_interval_ms: 400
